### ISSUE TITLE
The pinned Werkzeug version is incompatible with Python 3.8

### ISSUE THREAD

**Issue by megamorf** [miguelgrinberg/flask-celery-example#23]
```
Traceback (most recent call last):
  File "./app.py", line 10, in <module>
    app = Flask(__name__)
  File "/Users/megamorf/.local/share/virtualenvs/flask-celery-example--m1TFcnE/lib/python3.8/site-packages/flask/app.py", line 559, in __init__
    self.add_url_rule(
  File "/Users/megamorf/.local/share/virtualenvs/flask-celery-example--m1TFcnE/lib/python3.8/site-packages/flask/app.py", line 67, in wrapper_func
    return f(self, *args, **kwargs)
  File "/Users/megamorf/.local/share/virtualenvs/flask-celery-example--m1TFcnE/lib/python3.8/site-packages/flask/app.py", line 1217, in add_url_rule
    self.url_map.add(rule)
  File "/Users/megamorf/.local/share/virtualenvs/flask-celery-example--m1TFcnE/lib/python3.8/site-packages/werkzeug/routing.py", line 1388, in add
    rule.bind(self)
  File "/Users/megamorf/.local/share/virtualenvs/flask-celery-example--m1TFcnE/lib/python3.8/site-packages/werkzeug/routing.py", line 730, in bind
    self.compile()
  File "/Users/megamorf/.local/share/virtualenvs/flask-celery-example--m1TFcnE/lib/python3.8/site-packages/werkzeug/routing.py", line 794, in compile
    self._build = self._compile_builder(False).__get__(self, None)
  File "/Users/megamorf/.local/share/virtualenvs/flask-celery-example--m1TFcnE/lib/python3.8/site-packages/werkzeug/routing.py", line 951, in _compile_builder
    code = compile(module, "<werkzeug routing>", "exec")
TypeError: required field "type_ignores" missing from Module
(flask-celery-example)
```

See:
https://github.com/pallets/werkzeug/issues/1551

**Comment by miguelgrinberg** [comment]
Updated requirements.
