### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by bilalahmadj110** [miguelgrinberg/flask-celery-example#26]
```
Traceback (most recent call last):
  File "C:\Users\BILAL AHMAD\Downloads\Compressed\flask-celery-example-master\app.py", line 129, in <module>
    app.run(debug=True)
  File "C:\Users\BILAL AHMAD\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\app.py", line 985, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)
  File "C:\Users\BILAL AHMAD\AppData\Local\Programs\Python\Python38-32\lib\site-packages\flask\cli.py", line 670, in show_server_banner
    click.echo(message)
  File "C:\Users\BILAL AHMAD\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\utils.py", line 218, in echo
    file = _default_text_stdout()
  File "C:\Users\BILAL AHMAD\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\_compat.py", line 675, in func
    rv = wrapper_func()
  File "C:\Users\BILAL AHMAD\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\_compat.py", line 436, in get_text_stdout
    rv = _get_windows_console_stream(sys.stdout, encoding, errors)
  File "C:\Users\BILAL AHMAD\AppData\Local\Programs\Python\Python38-32\lib\site-packages\click\_winconsole.py", line 295, in _get_windows_console_stream
    func = _stream_factories.get(f.fileno())
io.UnsupportedOperation: fileno
```

**Comment by miguelgrinberg** [comment]
This has nothing to do with the code in this repository. See https://stackoverflow.com/questions/31080829/python-error-io-unsupportedoperation-fileno for something that appears related to your problem.
